spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/springSecurity_db}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
api.secret-key=${JWT_SECRET_KEY:8kDeempPf9W8Mz1AFc3LraxzbvrzbaD3YFAiCpWg0N2}
